apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: red-notes

resources:
  - namespace.yaml
  - backend-deploy.yaml
  - frontend-deploy.yaml
  - worker-deploy.yaml
  - postgres-statefulset.yaml
  - redis-deploy.yaml
  - secrets.yaml
  - configmap.yaml
  - network-policy.yaml
  - pdb.yaml
  - ingress.yaml