apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-network-policy
  namespace: secure-notes-apps
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      to:
        - pods:
            matchLabels:
              app: backend
    - from:
        - podSelector:
            matchLabels:
              app: backend
        - podSelector:
            matchLabels:
              app: worker
      to:
        - pods:
            matchLabels:
              app: postgres
        - pods:
            matchLabels:
              app: redis
