apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: red-notes
type: Opaque
data:
  POSTGRES_USER: ZGV2X3VzZXI=
  POSTGRES_PASSWORD: ZGV2X3Bhc3N3b3Jk
  POSTGRES_DB: c2VjdXJlX25vdGVz
  DATABASE_URL: cG9zdGdyZXNxbDovL2Rldl91c2VyOmRldl9wYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvc2VjdXJlX25vdGVzP3NjaGVtYT1wdWJsaWM=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: cGtfbGl2ZV9ZMnhsY21zdWJXVnFablV1WkdWMkpB
  CLERK_PUBLISHABLE_KEY: cGtfbGl2ZV9ZMnhsY21zdWJXVnFablV1WkdWMkpB
  CLERK_SECRET_KEY: c2tfbGl2ZV9GOUYyejZrSFkzaHZMN2U1am1CVzNJdzlTWUd3RWZyT2pCVDhUTWgwYXo=
  CLERK_WEBHOOK_SECRET: d2hzZWNfUTloQTJrUDIzNm9mZlYySlhneHlZOVp0V1IyS3BpMzk=
  API_URL: aHR0cHM6Ly9tZWhmdS5kZXY=