name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: "read"
  id-token: "write"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Update npm to latest
        run: npm install -g npm@latest
      - run: npm install
      - run: |
          cd apps/backend
          npm run test:ci

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.component }}
          tags: type=sha,format=long
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/${{ matrix.component }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/486703429318/locations/global/workloadIdentityPools/github-pool/providers/github-pool"
          service_account: "github-actions-deployer@project-c35b3362-c904-47c0-bbd.iam.gserviceaccount.com"

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "red-notes"
          location: "europe-central2"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/
          IMAGE_TAG="${{ github.sha }}"
          NAMESPACE="default"
          kubectl set image deployment/backend-deployment backend=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:sha-${IMAGE_TAG} -n $NAMESPACE
          kubectl rollout status deployment/backend-deployment -n $NAMESPACE --timeout=2m
